/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityIcon: typeof import('./components/icons/ActivityIcon.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    BackgroundEffects: typeof import('./components/effects/BackgroundEffects.vue')['default']
    BaseChart: typeof import('./components/charts/BaseChart.vue')['default']
    BellIcon: typeof import('./components/icons/BellIcon.vue')['default']
    BriefcaseIcon: typeof import('./components/icons/briefcaseIcon.vue')['default']
    ChartBarIcon: typeof import('./components/icons/ChartBarIcon.vue')['default']
    CogIcon: typeof import('./components/icons/CogIcon.vue')['default']
    DocumentIcon: typeof import('./components/icons/DocumentIcon.vue')['default']
    FundEstimateChart: typeof import('./components/charts/FundEstimateChart.vue')['default']
    FundHeatmap: typeof import('./components/charts/FundHeatmap.vue')['default']
    FundKLineChart: typeof import('./components/charts/FundKLineChart.vue')['default']
    HomeIcon: typeof import('./components/icons/HomeIcon.vue')['default']
    LegalPage: typeof import('./components/legal/LegalPage.vue')['default']
    LogoutIcon: typeof import('./components/icons/LogoutIcon.vue')['default']
    MenuIcon: typeof import('./components/icons/MenuIcon.vue')['default']
    PortfolioPieChart: typeof import('./components/charts/PortfolioPieChart.vue')['default']
    RealTimeQuoteChart: typeof import('./components/charts/RealTimeQuoteChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XIcon: typeof import('./components/icons/XIcon.vue')['default']
  }
}
